### ISSUE TITLE
A Strange Name

### ISSUE THREAD

**Issue by PiYuanZhouLv** [doki-theme/doki-theme-firefox#16]
> P.S. I'm sorry for my poor Engilsh. If you can communicate in Chinese freely, that would be better.

I found a strange name when I using this plugin. It looks like meaningless chars. I guess it may cause by the network, but reinstalling doesn't work. Is it a bug?

我在用这个插件时发现了一个奇怪的名字，那看上去像一串乱码。我猜测它可能是网络引起的，但重装不起作用。这是一个bug吗？

![图片](https://user-images.githubusercontent.com/95156880/156299684-67ec8d6c-b057-4ba8-b165-0f80ae8551c0.png)

The theme is named Sayori I think. the picture below is the shotcut of the new tab.

我认为这个主题的名字叫 Sayori。下面是新建标签页的截图。

![图片](https://user-images.githubusercontent.com/95156880/156300431-7c105a2a-6687-4565-94c6-4c36c36ee7b1.png)

**Comment by Unthrottled** [comment]
>这是一个bug吗？

是的，我忘了暗色的Sayori有奇怪的字 （[zalgo text](https://github.com/doki-theme/doki-master-theme/blob/e65a3cf1d278e266ba74470acba4c16a4c01d693/definitions/literature/sayori/dark/sayori.dark.master.definition.json#L4)). 我馬上修。

（我學習中文，但還沒有老師。所以我不知道我的語法錯了。:sweat_smile: )
