### ISSUE TITLE
a Uncomfortable Design in Content Type

### ISSUE THREAD

**Issue by PiYuanZhouLv** [doki-theme/doki-theme-firefox#17]
> P.S. I'm sorry for my poor Engilsh. If you can communicate in Chinese freely, that would be better.

I found a uncomfortable design in the Content Type -- it doesn't remember the content type users chose. When I want to turn the secondary content to the primary content, primary content has already been chosen and the apply button is disabled at the same time. I have to click secondary content and apply it, then continue to click primary content and apply it. It such a uncomfortable design, especially in the situation like when someone want to look through all theme.

我发现了Content Type中的一个令人不悦的设计——它不会记住用户选择的内容。当我想把第二内容调为第一内容时，“第一内容”的选项已经被选，并且“确定”按钮不可用。我不得不先选中第二内容后提交，再选择第一内容。这真是一个令人不悦的设计，尤其是在类似于浏览所有的主题之类的情景下。

![图片](https://user-images.githubusercontent.com/95156880/156302365-211c5727-cc79-4c8a-93a5-47e60c68b6f2.png)
(This is the secondary theme 这是第二内容)

![图片](https://user-images.githubusercontent.com/95156880/156302470-707c224b-8137-4d48-a23d-6d2a92acb368.png)
(And the primary has been chosen,and apply button is disabled “第一内容”已经被选，提交按钮不可用)

**Comment by Unthrottled** [comment]
这是预期的结果吗？

https://user-images.githubusercontent.com/15972415/156469052-7019e9c7-072e-4c92-b0b6-b16f7a1d3786.mp4
